### ISSUE TITLE
Results of the original paper

### ISSUE THREAD

**Issue by EastonWang** [NLPLearn/QANet#19]
Thanks for this great implementation.  I noticed that you mentioned in the README file that the original system can achieve EM: 72.5, F1: 81.4 after 150,000 training steps, and EM: 76.2, F1: 84.6 after 340,000 training steps.  But I didn't find this information in the original paper. It seems that the original system takes much longer time to train? Could you show me where to get this information? Or did you infer that from other statistics?

**Comment by localminimum** [comment]
Hi @EastonWang , there has been a revision in the paper since I wrote down that statistics. You can find the results by the authors from the original paper. Check subsection 4.1.2. I will update the readme now. Thanks.
