### ISSUE TITLE
training on "Answer not available" ?

### ISSUE THREAD

**Issue by nehaboob** [NLPLearn/QANet#24]
Any suggestions on how to train network on "Not available" answer for the questions which cannot be answered from the context.

**Comment by localminimum** [comment]
Hi @nehaboob . To answer the question from outside of the given context paragraph you need to replace the answer pointer network to a decoder network with fixed dictionary size. You should expect the performance drop since you are giving up the assumption that the answer lies within the context.

**Comment by nehaboob** [comment]
since network is trained to predict probability of start and end of answer context, can we use that probability to find out if answer might not be present in the context ?

**Comment by theSage21** [comment]
A good method might be to add a dummy word in front of each paragraph and then generate multiple samples (maybe by matching the question to a wrong paragraph) where the "answer" is the dummy word added in front of the paragraph.

During inference then the "no answer found" case is when the system predicts that default word.

**Comment by nehaboob** [comment]
Great. With this we can avoid tuning a probability threshold and can keep the assumption that answer lies in the context. I will try this.

**Comment by localminimum** [comment]
I'll close this for now. If problems arise feel free to reopen this.

**Comment by nehaboob** [comment]
Sure. Thanks.
